### PR TITLE
Fix the build 

### PR DESCRIPTION
**Pull request by mrloop**
Running `yarn ember try:each` would fail on recent ember versions. The PR makes the minimal updates to get the project building again. Can be reviewed commit by commit. There are still a bunch of warnings that can be cleaned up in subsequent PRs.

- https://www.notion.so/qonto/Fork-and-fix-ember-api-actions-build-184cb624f8874f9db8af0566834c056b

### CODE REVIEW

**Comment by zeppelin** [comment]
@mrloop 👍 LGTM

One question: why `settled` is now required for the test suite to pass? Did it work for earlier Ember versions and stopped for newer ones?

**Comment by mrloop** [comment]
> One question: why settled is now required for the test suite to pass? Did it work for earlier Ember versions and stopped for newer ones?

Two questions ;) 

> Did it work for earlier Ember versions

Yes, think it's breaking for 4.x

> Why `settled` 

Not sure of root cause, want to do minimal required to get the build working. Hoping that `settled` can be removed in future MRs, maybe when `@ember/test-helpers` is updated or some other dependency?

**Comment by mrloop** [comment]
@dbendaou should @zeppelin be added as member to qonto, then he can approve my MR :)

**Comment by dbendaou** [comment]
Invite sent!

**Pull request merged**
